# Generated by Django 3.2.25 on 2024-12-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numconversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textitem', models.CharField(max_length=400)),
                ('numberres', models.IntegerField()),
            ],
        ),
    ]
